### ISSUE TITLE
`page:finish` hook won't be triggered

### ISSUE THREAD

**Issue by sxzz** [ijkml/nuxt-umami#102] opened 2024-05-06 05:44 UTC
If [ssr](https://nuxt.com/docs/api/nuxt-config#ssr) option is disabled, then `page:finish` hook won't be triggered.

https://github.com/ijkml/nuxt-umami/blob/6de77d16c3e98522e2f72ed9ee1365b4b2041eb0/plugins/umami.ts#L14-L19

**Comment by ijkml** [comment] 2024-05-06 15:41
Oh, boy... I'll look into this, thanks @sxzz.

**Comment by ijkml** [comment] 2024-05-07 15:32
Hello again, @sxzz.
I finally had a chance but I couldn't reproduce it. The hook seems to trigger with `ssr: false` :shrug:.
Anyway, could you take a look at this repro and let me know if I missed something?
https://stackblitz.com/edit/nuxt-umami?file=nuxt.config.ts

Thanks, again.

**Comment by sxzz** [comment] 2024-05-12 12:21
Seems not relate to SSR, but relate to Suspense

Minimal reproduction repo: https://github.com/sxzz/nuxt-page-finish

**Comment by ijkml** [comment] 2024-05-15 11:43
Yeah, you're right. It is related to Suspense.
But, the hook triggers when you add `<NuxtPage />`.
Repo: https://github.com/ijkml/nuxt-page-finish

Will look into how much of an effect this has 'cause the code is for `autoTrack` (useful when you have pages). 
https://github.com/ijkml/nuxt-umami/blob/6de77d16c3e98522e2f72ed9ee1365b4b2041eb0/plugins/umami.ts#L14-L19

How did you find the bug, please?

**Comment by sxzz** [comment] 2024-05-15 11:51
I have an SPA project that doesn't automatically track pages. To fix this, I manually added another plugin using `app:mounted` hook.

https://github.com/sxzz/ast-explorer/blob/main/plugins/umami.ts

**Comment by ijkml** [comment] 2024-05-15 13:12
Absolutely right, it is a `<NuxtPage>` / `Suspense` thing.

I'm stuck. Do you have any suggestions on a fix for this?

Also, instead of a plugin, `onMounted(() => umTrackView())` in `app.vue` might work, no?

**Comment by sxzz** [comment] 2024-05-16 04:27
Of course, it works. Can we use hook `app:mounted` (with 300ms delay), instead of `page:finish`?

**Comment by ijkml** [comment] 2024-05-18 08:54
Unfortunately, no.
`app:mounted` is only triggered once (https://nuxt.com/docs/api/advanced/hooks#app-hooks-runtime).

Mean time, I would add this behavior to faqs/quirks :+1:.

**Closed** 2024-05-20 14:08 UTC
Labels: quirk
